### ISSUE TITLE
Implement TAB completion in the console/shell

### ISSUE THREAD

**Issue by uralets** [dosemu2/comcom32#57] opened 2022-03-08 18:44 UTC
subj

It's almost reflectory - so when the user hits TAB and instead of DOSBOX-like (or shell-like or cmd-like) completion gets tab char or something inserted and has to backspace over a bunch (BIG BUNCH) of spaces it's VERY ANNOYING.

Sorry for the caps.

**Comment by stsp** [comment] 2022-03-08 22:28
Dupe of #11 
If that annoys you that much, just
put freecom.exe to C and symlink
to command.com and you are fine.
Our default shell is so far very minimalistic.

**Closed by stsp** 2022-03-08 22:28 UTC
